//! Prefix tables for IP-range-based provider detection.
//!
//! One [`RangeTable`] holds every provider's published ranges, keyed by
//! longest-prefix match so a lookup is O(prefix length) regardless of how
//! many providers are loaded. Built once at startup in a background task
//! (see `providers::signatures::load_all`) and then only read.

use std::net::IpAddr;
use std::path::Path;

use chrono::{DateTime, Utc};
use ip_network::IpNetwork;
use ip_network_table::IpNetworkTable;

use super::signatures::LoadedSignature;
use super::Layer;

/// One published range, tagged with the provider and (when the source
/// distinguishes it) the service/region it belongs to.
#[derive(Debug, Clone)]
pub struct RangeEntry {
    pub provider_id: String,
    pub layer: Layer,
    /// A service tag from the source, e.g. AWS's `CLOUDFRONT` or `EC2`.
    pub service: Option<String>,
    pub region: Option<String>,
    /// Which configured source this came from, e.g. `ips-v4` or
    /// `ip-ranges.json`, shown in evidence strings.
    pub source_name: String,
}

/// The result of a successful [`RangeTable::lookup`].
#[derive(Debug, Clone)]
pub struct RangeMatch {
    pub provider_id: String,
    pub layer: Layer,
    pub service: Option<String>,
    pub region: Option<String>,
    pub source_name: String,
    pub prefix: IpNetwork,
}

/// A merged, longest-prefix-match table of every provider's IP ranges.
pub struct RangeTable {
    table: IpNetworkTable<RangeEntry>,
}

// `IpNetworkTable`'s `Debug`/`Default`/`Clone` derives require `RangeEntry:
// Debug + Default + Clone` (an over-eager bound from its own derive), which
// we don't want to give `RangeEntry` just to satisfy them, so these are
// implemented by hand instead.
impl std::fmt::Debug for RangeTable {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let (v4, v6) = self.table.len();
        f.debug_struct("RangeTable")
            .field("ipv4_prefixes", &v4)
            .field("ipv6_prefixes", &v6)
            .finish()
    }
}

impl Default for RangeTable {
    fn default() -> Self {
        Self::new()
    }
}

// Rebuilds from scratch (rather than deep-cloning the backend), which is
// just as cheap for our data sizes and lets a freshly rebuilt table be
// swapped into shared state without holding a lock during the swap.
impl Clone for RangeTable {
    fn clone(&self) -> Self {
        let mut table = IpNetworkTable::new();
        for (net, entry) in self.table.iter() {
            table.insert(net, entry.clone());
        }
        Self { table }
    }
}

impl RangeTable {
    pub fn new() -> Self {
        Self {
            table: IpNetworkTable::new(),
        }
    }

    /// Inserts one range. Later inserts of an overlapping-but-distinct
    /// prefix coexist fine; an exact-duplicate prefix replaces the earlier
    /// entry (last writer wins), which only matters when the same provider
    /// is loaded from two sources.
    pub fn insert(&mut self, prefix: IpNetwork, entry: RangeEntry) {
        self.table.insert(prefix, entry);
    }

    /// Number of (v4, v6) prefixes currently loaded.
    pub fn len(&self) -> (usize, usize) {
        self.table.len()
    }

    pub fn is_empty(&self) -> bool {
        self.table.is_empty()
    }

    /// Finds the most specific range containing `ip`, if any.
    pub fn lookup(&self, ip: IpAddr) -> Option<RangeMatch> {
        let (prefix, entry) = self.table.longest_match(ip)?;
        Some(RangeMatch {
            provider_id: entry.provider_id.clone(),
            layer: entry.layer,
            service: entry.service.clone(),
            region: entry.region.clone(),
            source_name: entry.source_name.clone(),
            prefix,
        })
    }
}

/// Files embedded from `data/snapshot/` at build time, as
/// `(filename, contents)` pairs. Generated by `build.rs`.
static EMBEDDED_SNAPSHOT: &[(&str, &str)] =
    &include!(concat!(env!("OUT_DIR"), "/embedded_snapshot.rs"));

fn embedded_file(filename: &str) -> Option<&'static str> {
    EMBEDDED_SNAPSHOT
        .iter()
        .find(|(name, _)| *name == filename)
        .map(|(_, contents)| *contents)
}

/// When the bundled snapshot (`data/snapshot/`) was generated, from its
/// embedded `GENERATED_AT` marker. `None` only if the snapshot somehow
/// wasn't embedded at build time.
pub fn snapshot_generated_at() -> Option<DateTime<Utc>> {
    embedded_file("GENERATED_AT").and_then(|s| s.trim().parse().ok())
}

/// The snapshot/cache filename a provider's Nth range source uses:
/// `<provider_id>-<index>.<ext>`.
pub fn source_filename(provider_id: &str, index: usize, format: super::formats::Format) -> String {
    format!("{provider_id}-{index}.{}", format.file_extension())
}

/// One source that failed to load (parse error, or a source with neither a
/// cache file nor a bundled snapshot). Collected rather than propagated so
/// one broken provider doesn't stop the others from loading.
#[derive(Debug, Clone)]
pub struct SourceLoadError {
    pub provider_id: String,
    pub url: String,
    pub message: String,
}

/// The result of building a [`RangeTable`] from the embedded snapshot and
/// (when present) the on-disk cache.
#[derive(Debug, Clone)]
pub struct RangeLoadReport {
    pub table: RangeTable,
    /// When the bundled snapshot was last regenerated (from `GENERATED_AT`).
    pub snapshot_generated_at: Option<DateTime<Utc>>,
    /// True if at least one source was read from the on-disk cache rather
    /// than the embedded snapshot.
    pub used_cache: bool,
    pub errors: Vec<SourceLoadError>,
}

/// Builds a [`RangeTable`] from every provider's configured range sources.
/// For each source, a cache file (in `cache_dir`, freshened by
/// `netloupe update-data`) takes precedence over the file bundled at build
/// time; a source with neither is skipped, not an error, since a
/// user-defined provider may not have a snapshot.
///
/// This does blocking file I/O and should be called from a background
/// task (`tokio::task::spawn_blocking`), never on the UI event loop.
pub fn load(signatures: &[LoadedSignature], cache_dir: Option<&Path>) -> RangeLoadReport {
    let mut table = RangeTable::new();
    let mut errors = Vec::new();
    let mut used_cache = false;

    for loaded in signatures {
        let Some(ranges) = &loaded.ranges else {
            continue;
        };
        let provider_id = &loaded.signature.id;

        for (index, source) in ranges.sources.iter().enumerate() {
            let filename = source_filename(provider_id, index, source.format);

            let cached = cache_dir.and_then(|dir| {
                let path = dir.join(&filename);
                std::fs::read_to_string(&path).ok()
            });
            let (data, from_cache) = match cached {
                Some(data) => (Some(data), true),
                None => (embedded_file(&filename).map(str::to_string), false),
            };
            let Some(data) = data else { continue };
            used_cache |= from_cache;

            match source.format.parse(&data) {
                Ok(parsed) => {
                    for range in parsed {
                        let layer = range
                            .service
                            .as_deref()
                            .and_then(|service| ranges.service_layers.get(service))
                            .copied()
                            .unwrap_or(ranges.default_layer);
                        table.insert(
                            range.prefix,
                            RangeEntry {
                                provider_id: provider_id.clone(),
                                layer,
                                service: range.service,
                                region: range.region,
                                source_name: filename.clone(),
                            },
                        );
                    }
                }
                Err(err) => errors.push(SourceLoadError {
                    provider_id: provider_id.clone(),
                    url: source.url.clone(),
                    message: err.to_string(),
                }),
            }
        }
    }

    RangeLoadReport {
        table,
        snapshot_generated_at: snapshot_generated_at(),
        used_cache,
        errors,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn entry(provider: &str) -> RangeEntry {
        RangeEntry {
            provider_id: provider.to_string(),
            layer: Layer::Edge,
            service: None,
            region: None,
            source_name: "test".to_string(),
        }
    }

    #[test]
    fn longest_prefix_wins() {
        let mut t = RangeTable::new();
        t.insert("104.16.0.0/12".parse().unwrap(), entry("cloudflare"));
        t.insert("104.16.0.0/16".parse().unwrap(), entry("cloudflare-inner"));

        let m = t.lookup("104.16.1.1".parse().unwrap()).unwrap();
        assert_eq!(m.provider_id, "cloudflare-inner");
    }

    #[test]
    fn no_match_returns_none() {
        let t = RangeTable::new();
        assert!(t.lookup("1.2.3.4".parse().unwrap()).is_none());
    }

    #[test]
    fn matches_ipv6() {
        let mut t = RangeTable::new();
        t.insert("2606:4700::/32".parse().unwrap(), entry("cloudflare"));
        let m = t.lookup("2606:4700::1111".parse().unwrap()).unwrap();
        assert_eq!(m.provider_id, "cloudflare");
    }

    #[test]
    fn clone_preserves_entries() {
        let mut t = RangeTable::new();
        t.insert("10.0.0.0/8".parse().unwrap(), entry("acme"));
        let cloned = t.clone();
        let m = cloned.lookup("10.1.2.3".parse().unwrap()).unwrap();
        assert_eq!(m.provider_id, "acme");
    }

    #[test]
    fn load_builds_table_from_embedded_snapshot() {
        let loaded = super::super::signatures::load_all(None).unwrap();
        let report = load(&loaded, None);
        assert!(!report.table.is_empty());
        // A known Cloudflare edge IP from the bundled snapshot.
        let m = report.table.lookup("173.245.48.1".parse().unwrap());
        assert!(m.is_some_and(|m| m.provider_id == "cloudflare"));
        assert!(report.snapshot_generated_at.is_some());
    }

    #[test]
    fn load_prefers_cache_dir_over_snapshot() {
        let loaded = super::super::signatures::load_all(None).unwrap();
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("cloudflare-0.txt"), "192.0.2.0/24\n").unwrap();
        // Source 1 (ips-v6) has no cache override, so it still falls back
        // to the embedded snapshot.
        let report = load(&loaded, Some(dir.path()));
        assert!(report.used_cache);
        let m = report.table.lookup("192.0.2.1".parse().unwrap()).unwrap();
        assert_eq!(m.provider_id, "cloudflare");
        assert_eq!(m.source_name, "cloudflare-0.txt");
        // The real snapshot's first range should now be absent, since the
        // cache file replaced it rather than merging with it.
        assert!(report
            .table
            .lookup("173.245.48.1".parse().unwrap())
            .is_none());
    }

    #[test]
    fn load_records_a_per_source_error_without_dropping_other_providers() {
        let loaded = super::super::signatures::load_all(None).unwrap();
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("aws-0.json"),
            "{\"not\": \"the right shape\"}",
        )
        .unwrap();
        let report = load(&loaded, Some(dir.path()));
        assert!(report.errors.iter().any(|e| e.provider_id == "aws"));
        // Cloudflare's own sources are unaffected by AWS's broken cache file.
        assert!(report
            .table
            .lookup("173.245.48.1".parse().unwrap())
            .is_some());
    }
}
