//! Loading and validating provider signature files (`data/providers/*.toml`).
//!
//! Signature files are embedded into the binary at build time (see
//! `build.rs`) so detection works with zero setup, plus an optional
//! extra directory of user-defined signatures (e.g. for an internal
//! company IP range) loaded from disk at startup.

use std::collections::BTreeMap;
use std::path::Path;

use serde::Deserialize;
use thiserror::Error;

use super::formats::Format;
use super::{Layer, Signal, SignalKind, Signature};

/// Files embedded from `data/providers/*.toml` at build time, as
/// `(filename, contents)` pairs. Generated by `build.rs`.
pub static EMBEDDED_SIGNATURES: &[(&str, &str)] =
    &include!(concat!(env!("OUT_DIR"), "/embedded_providers.rs"));

/// One IP-range source configured for a provider, e.g. Cloudflare's
/// `ips-v4` list or AWS's `ip-ranges.json`.
#[derive(Debug, Clone)]
pub struct RangeSource {
    pub url: String,
    pub format: Format,
}

/// A provider's `[ranges]` table: where to fetch prefixes from and how to
/// classify them into layers.
#[derive(Debug, Clone)]
pub struct RangesConfig {
    pub sources: Vec<RangeSource>,
    /// Layer to report when a matched prefix carries no service tag, or one
    /// the map below doesn't recognize.
    pub default_layer: Layer,
    /// Maps a source's service tag (e.g. AWS's `CLOUDFRONT`) to the layer
    /// it should be reported under.
    pub service_layers: BTreeMap<String, Layer>,
}

/// A [`Signature`] plus its (not-yet-fetched) range configuration, as
/// produced by parsing one TOML file.
#[derive(Debug, Clone)]
pub struct LoadedSignature {
    pub signature: Signature,
    pub ranges: Option<RangesConfig>,
}

/// Errors validating a single signature file.
#[derive(Debug, Error)]
pub enum SignatureError {
    #[error("invalid TOML: {0}")]
    Toml(#[from] Box<toml::de::Error>),
    #[error("invalid glob pattern {pattern:?} in signal for {provider}: {source}")]
    Glob {
        provider: String,
        pattern: String,
        #[source]
        source: globset::Error,
    },
    #[error("invalid regex {regex:?} in signal for {provider}: {source}")]
    Regex {
        provider: String,
        regex: String,
        #[source]
        source: Box<regex::Error>,
    },
    #[error("provider {provider}: signal of type {kind:?} needs a {field} field")]
    MissingField {
        provider: String,
        kind: SignalKind,
        field: &'static str,
    },
    #[error("provider {0} appears more than once")]
    DuplicateId(String),
}

/// Errors loading the whole signature set.
#[derive(Debug, Error)]
pub enum SignatureLoadError {
    #[error(transparent)]
    Invalid(#[from] SignatureError),
    #[error("failed to read {path}: {source}")]
    Read {
        path: std::path::PathBuf,
        #[source]
        source: std::io::Error,
    },
}

#[derive(Debug, Deserialize)]
struct RawSignature {
    id: String,
    name: String,
    #[serde(default)]
    kind: Vec<String>,
    #[serde(default)]
    ranges: Option<RawRanges>,
    #[serde(default)]
    asn: Option<RawAsn>,
    #[serde(default, rename = "signal")]
    signals: Vec<RawSignal>,
}

#[derive(Debug, Deserialize)]
struct RawRanges {
    sources: Vec<RawSource>,
    #[serde(default)]
    default_layer: Option<Layer>,
    #[serde(default)]
    service_layers: BTreeMap<String, Layer>,
}

#[derive(Debug, Deserialize)]
struct RawSource {
    url: String,
    format: Format,
}

#[derive(Debug, Deserialize)]
struct RawAsn {
    #[serde(default)]
    numbers: Vec<u32>,
}

#[derive(Debug, Deserialize)]
struct RawSignal {
    layer: Layer,
    #[serde(rename = "type")]
    kind: SignalKind,
    weight: u32,
    #[serde(default)]
    name: Option<String>,
    #[serde(default)]
    pattern: Option<String>,
    #[serde(default)]
    value_regex: Option<String>,
}

/// Parses and validates one signature file's TOML text.
pub fn parse_and_validate(text: &str) -> Result<LoadedSignature, SignatureError> {
    let raw: RawSignature = toml::from_str(text).map_err(Box::new)?;

    let signals = raw
        .signals
        .into_iter()
        .map(|s| compile_signal(&raw.id, s))
        .collect::<Result<Vec<_>, _>>()?;

    let ranges = raw.ranges.map(|r| RangesConfig {
        sources: r
            .sources
            .into_iter()
            .map(|s| RangeSource {
                url: s.url,
                format: s.format,
            })
            .collect(),
        default_layer: r.default_layer.unwrap_or(Layer::Origin),
        service_layers: r.service_layers,
    });

    Ok(LoadedSignature {
        signature: Signature {
            id: raw.id,
            name: raw.name,
            kind: raw.kind,
            asns: raw.asn.map(|a| a.numbers).unwrap_or_default(),
            signals,
        },
        ranges,
    })
}

fn compile_signal(provider: &str, raw: RawSignal) -> Result<Signal, SignatureError> {
    let value_regex = raw
        .value_regex
        .map(|re| {
            regex::Regex::new(&re).map_err(|source| SignatureError::Regex {
                provider: provider.to_string(),
                regex: re,
                source: Box::new(source),
            })
        })
        .transpose()?;

    let pattern = raw
        .pattern
        .map(|p| {
            globset::Glob::new(&p)
                .map(|g| g.compile_matcher())
                .map_err(|source| SignatureError::Glob {
                    provider: provider.to_string(),
                    pattern: p,
                    source,
                })
        })
        .transpose()?;

    if matches!(raw.kind, SignalKind::Header) && raw.name.is_none() {
        return Err(SignatureError::MissingField {
            provider: provider.to_string(),
            kind: raw.kind,
            field: "name",
        });
    }
    if !matches!(raw.kind, SignalKind::Header) && pattern.is_none() {
        return Err(SignatureError::MissingField {
            provider: provider.to_string(),
            kind: raw.kind,
            field: "pattern",
        });
    }

    Ok(Signal {
        layer: raw.layer,
        kind: raw.kind,
        weight: raw.weight,
        name: raw.name,
        value_regex,
        pattern,
    })
}

/// Loads and validates every embedded signature, plus any `*.toml` files in
/// `extra_dir` (for user-defined providers). Fails loudly on the first
/// invalid file: a broken signature is a configuration bug, not a runtime
/// condition to degrade gracefully from.
pub fn load_all(extra_dir: Option<&Path>) -> Result<Vec<LoadedSignature>, SignatureLoadError> {
    let mut out = Vec::with_capacity(EMBEDDED_SIGNATURES.len());
    let mut seen_ids = std::collections::BTreeSet::new();

    for (filename, text) in EMBEDDED_SIGNATURES {
        let loaded = parse_and_validate(text).map_err(|e| SignatureLoadError::Read {
            path: std::path::PathBuf::from(filename),
            source: std::io::Error::other(e.to_string()),
        })?;
        if !seen_ids.insert(loaded.signature.id.clone()) {
            return Err(SignatureError::DuplicateId(loaded.signature.id.clone()).into());
        }
        out.push(loaded);
    }

    if let Some(dir) = extra_dir {
        if dir.is_dir() {
            let mut paths: Vec<_> = std::fs::read_dir(dir)
                .map_err(|source| SignatureLoadError::Read {
                    path: dir.to_path_buf(),
                    source,
                })?
                .filter_map(|e| e.ok())
                .map(|e| e.path())
                .filter(|p| p.extension().is_some_and(|ext| ext == "toml"))
                .collect();
            paths.sort();
            for path in paths {
                let text =
                    std::fs::read_to_string(&path).map_err(|source| SignatureLoadError::Read {
                        path: path.clone(),
                        source,
                    })?;
                let loaded = parse_and_validate(&text)?;
                if !seen_ids.insert(loaded.signature.id.clone()) {
                    return Err(SignatureError::DuplicateId(loaded.signature.id.clone()).into());
                }
                out.push(loaded);
            }
        }
    }

    Ok(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    const CLOUDFLARE_TOML: &str = r#"
        id = "cloudflare"
        name = "Cloudflare"
        kind = ["cdn", "dns", "waf"]

        [ranges]
        sources = [
          { url = "https://www.cloudflare.com/ips-v4", format = "plain" },
        ]

        [[signal]]
        layer = "edge"
        type = "header"
        name = "cf-ray"
        weight = 60

        [[signal]]
        layer = "edge"
        type = "header"
        name = "server"
        value_regex = "(?i)^cloudflare$"
        weight = 50

        [[signal]]
        layer = "dns"
        type = "ns"
        pattern = "*.ns.cloudflare.com"
        weight = 90
    "#;

    #[test]
    fn parses_the_example_from_claude_md() {
        let loaded = parse_and_validate(CLOUDFLARE_TOML).unwrap();
        assert_eq!(loaded.signature.id, "cloudflare");
        assert_eq!(loaded.signature.signals.len(), 3);
        assert_eq!(loaded.ranges.unwrap().sources.len(), 1);
    }

    #[test]
    fn rejects_header_signal_without_name() {
        let toml_str = r#"
            id = "x"
            name = "X"
            [[signal]]
            layer = "edge"
            type = "header"
            weight = 10
        "#;
        assert!(parse_and_validate(toml_str).is_err());
    }

    #[test]
    fn rejects_pattern_signal_without_pattern() {
        let toml_str = r#"
            id = "x"
            name = "X"
            [[signal]]
            layer = "dns"
            type = "ns"
            weight = 10
        "#;
        assert!(parse_and_validate(toml_str).is_err());
    }

    #[test]
    fn rejects_invalid_glob() {
        let toml_str = r#"
            id = "x"
            name = "X"
            [[signal]]
            layer = "dns"
            type = "ns"
            pattern = "["
            weight = 10
        "#;
        assert!(parse_and_validate(toml_str).is_err());
    }

    #[test]
    fn rejects_invalid_regex() {
        let toml_str = r#"
            id = "x"
            name = "X"
            [[signal]]
            layer = "edge"
            type = "header"
            name = "server"
            value_regex = "("
            weight = 10
        "#;
        assert!(parse_and_validate(toml_str).is_err());
    }

    #[test]
    fn loads_all_embedded_signatures_without_error() {
        let loaded = load_all(None).expect("embedded signatures must be valid");
        assert!(!loaded.is_empty());
        let ids: std::collections::BTreeSet<_> =
            loaded.iter().map(|l| l.signature.id.clone()).collect();
        assert!(ids.contains("cloudflare"));
    }

    #[test]
    fn loads_extra_user_defined_signatures() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(
            dir.path().join("internal.toml"),
            r#"
                id = "internal"
                name = "Internal Network"
                kind = ["internal"]
                [ranges]
                sources = []
            "#,
        )
        .unwrap();
        let loaded = load_all(Some(dir.path())).unwrap();
        assert!(loaded.iter().any(|l| l.signature.id == "internal"));
    }
}
